from collections.abc import AsyncIterator, Callable as Callable, Iterator, Sequence
from langchain_core.language_models import BaseChatModel as BaseChatModel, LanguageModelInput
from langchain_core.messages import AIMessage as AIMessage
from langchain_core.runnables import Runnable, RunnableConfig
from langchain_core.runnables.schema import StreamEvent as StreamEvent
from langchain_core.tools import BaseTool as BaseTool
from langchain_core.tracers import RunLog as RunLog, RunLogPatch as RunLogPatch
from pydantic import BaseModel as BaseModel
from typing import Any, Literal, TypeAlias, overload
from typing_extensions import override

@overload
def init_chat_model(model: str, *, model_provider: str | None = None, configurable_fields: None = None, config_prefix: str | None = None, **kwargs: Any) -> BaseChatModel: ...
@overload
def init_chat_model(model: None = None, *, model_provider: str | None = None, configurable_fields: None = None, config_prefix: str | None = None, **kwargs: Any) -> _ConfigurableModel: ...
@overload
def init_chat_model(model: str | None = None, *, model_provider: str | None = None, configurable_fields: Literal['any'] | list[str] | tuple[str, ...] = ..., config_prefix: str | None = None, **kwargs: Any) -> _ConfigurableModel: ...

class _ConfigurableModel(Runnable[LanguageModelInput, Any]):
    def __init__(self, *, default_config: dict[str, Any] | None = None, configurable_fields: Literal['any'] | list[str] | tuple[str, ...] = 'any', config_prefix: str = '', queued_declarative_operations: Sequence[tuple[str, tuple[Any, ...], dict[str, Any]]] = ()) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def with_config(self, config: RunnableConfig | None = None, **kwargs: Any) -> _ConfigurableModel: ...
    @property
    @override
    def InputType(self) -> TypeAlias: ...
    @override
    def invoke(self, input: LanguageModelInput, config: RunnableConfig | None = None, **kwargs: Any) -> Any: ...
    @override
    async def ainvoke(self, input: LanguageModelInput, config: RunnableConfig | None = None, **kwargs: Any) -> Any: ...
    @override
    def stream(self, input: LanguageModelInput, config: RunnableConfig | None = None, **kwargs: Any | None) -> Iterator[Any]: ...
    @override
    async def astream(self, input: LanguageModelInput, config: RunnableConfig | None = None, **kwargs: Any | None) -> AsyncIterator[Any]: ...
    def batch(self, inputs: list[LanguageModelInput], config: RunnableConfig | list[RunnableConfig] | None = None, *, return_exceptions: bool = False, **kwargs: Any | None) -> list[Any]: ...
    async def abatch(self, inputs: list[LanguageModelInput], config: RunnableConfig | list[RunnableConfig] | None = None, *, return_exceptions: bool = False, **kwargs: Any | None) -> list[Any]: ...
    def batch_as_completed(self, inputs: Sequence[LanguageModelInput], config: RunnableConfig | Sequence[RunnableConfig] | None = None, *, return_exceptions: bool = False, **kwargs: Any) -> Iterator[tuple[int, Any | Exception]]: ...
    async def abatch_as_completed(self, inputs: Sequence[LanguageModelInput], config: RunnableConfig | Sequence[RunnableConfig] | None = None, *, return_exceptions: bool = False, **kwargs: Any) -> AsyncIterator[tuple[int, Any]]: ...
    @override
    def transform(self, input: Iterator[LanguageModelInput], config: RunnableConfig | None = None, **kwargs: Any | None) -> Iterator[Any]: ...
    @override
    async def atransform(self, input: AsyncIterator[LanguageModelInput], config: RunnableConfig | None = None, **kwargs: Any | None) -> AsyncIterator[Any]: ...
    @overload
    @override
    def astream_log(self, input: Any, config: RunnableConfig | None = None, *, diff: Literal[True] = True, with_streamed_output_list: bool = True, include_names: Sequence[str] | None = None, include_types: Sequence[str] | None = None, include_tags: Sequence[str] | None = None, exclude_names: Sequence[str] | None = None, exclude_types: Sequence[str] | None = None, exclude_tags: Sequence[str] | None = None, **kwargs: Any) -> AsyncIterator[RunLogPatch]: ...
    @overload
    @override
    def astream_log(self, input: Any, config: RunnableConfig | None = None, *, diff: Literal[False], with_streamed_output_list: bool = True, include_names: Sequence[str] | None = None, include_types: Sequence[str] | None = None, include_tags: Sequence[str] | None = None, exclude_names: Sequence[str] | None = None, exclude_types: Sequence[str] | None = None, exclude_tags: Sequence[str] | None = None, **kwargs: Any) -> AsyncIterator[RunLog]: ...
    @override
    async def astream_events(self, input: Any, config: RunnableConfig | None = None, *, version: Literal['v1', 'v2'] = 'v2', include_names: Sequence[str] | None = None, include_types: Sequence[str] | None = None, include_tags: Sequence[str] | None = None, exclude_names: Sequence[str] | None = None, exclude_types: Sequence[str] | None = None, exclude_tags: Sequence[str] | None = None, **kwargs: Any) -> AsyncIterator[StreamEvent]: ...
    def bind_tools(self, tools: Sequence[dict[str, Any] | type[BaseModel] | Callable[..., Any] | BaseTool], **kwargs: Any) -> Runnable[LanguageModelInput, AIMessage]: ...
    def with_structured_output(self, schema: dict[str, Any] | type[BaseModel], **kwargs: Any) -> Runnable[LanguageModelInput, dict[str, Any] | BaseModel]: ...
