[project]
name = "rag-against-the-machine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.13.0",
    "bm25s>=0.3.9",
    "chromadb>=1.5.9",
    "fire>=0.7.1",
    "flake8>=7.3.0",
    "flashrank>=0.2.10",
    "mypy>=2.0.0",
    "ollama>=0.6.2",
    "pip>=26.1.1",
    "pudb>=2025.1.5",
    "pydantic>=2.13.4",
    "sentence-transformers>=5.6.0",
    "torch>=2.11.0",
    "tqdm>=4.67.3",
    "transformers<5.0.0",
]
