import abc
import subprocess
import typing
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path

__all__ = ['BaseExecutionPolicy', 'CodexSandboxExecutionPolicy', 'DockerExecutionPolicy', 'HostExecutionPolicy']

@dataclass
class BaseExecutionPolicy(abc.ABC, metaclass=abc.ABCMeta):
    command_timeout: float = ...
    startup_timeout: float = ...
    termination_timeout: float = ...
    max_output_lines: int = ...
    max_output_bytes: int | None = ...
    def __post_init__(self) -> None: ...
    @abc.abstractmethod
    def spawn(self, *, workspace: Path, env: Mapping[str, str], command: Sequence[str]) -> subprocess.Popen[str]: ...

@dataclass
class HostExecutionPolicy(BaseExecutionPolicy):
    cpu_time_seconds: int | None = ...
    memory_bytes: int | None = ...
    create_process_group: bool = ...
    def __post_init__(self) -> None: ...
    def spawn(self, *, workspace: Path, env: Mapping[str, str], command: Sequence[str]) -> subprocess.Popen[str]: ...

@dataclass
class CodexSandboxExecutionPolicy(BaseExecutionPolicy):
    binary: str = ...
    platform: typing.Literal['auto', 'macos', 'linux'] = ...
    config_overrides: Mapping[str, typing.Any] = field(default_factory=dict)
    def spawn(self, *, workspace: Path, env: Mapping[str, str], command: Sequence[str]) -> subprocess.Popen[str]: ...

@dataclass
class DockerExecutionPolicy(BaseExecutionPolicy):
    binary: str = ...
    image: str = ...
    remove_container_on_exit: bool = ...
    network_enabled: bool = ...
    extra_run_args: Sequence[str] | None = ...
    memory_bytes: int | None = ...
    cpu_time_seconds: typing.Any | None = ...
    cpus: str | None = ...
    read_only_rootfs: bool = ...
    user: str | None = ...
    def __post_init__(self) -> None: ...
    def spawn(self, *, workspace: Path, env: Mapping[str, str], command: Sequence[str]) -> subprocess.Popen[str]: ...
