from collections.abc import Awaitable, Callable, Iterable, Sequence
from dataclasses import dataclass
from langchain.agents.middleware.types import AgentMiddleware, AgentState, ContextT, ModelRequest, ModelResponse, ResponseT
from langchain_core.messages import AIMessage, AnyMessage, BaseMessage
from typing import Literal
from typing_extensions import Protocol

__all__ = ['ClearToolUsesEdit', 'ContextEditingMiddleware']

TokenCounter = Callable[[Sequence[BaseMessage]], int]

class ContextEdit(Protocol):
    def apply(self, messages: list[AnyMessage], *, count_tokens: TokenCounter) -> None: ...

@dataclass(slots=True)
class ClearToolUsesEdit(ContextEdit):
    trigger: int = ...
    clear_at_least: int = ...
    keep: int = ...
    clear_tool_inputs: bool = ...
    exclude_tools: Sequence[str] = ...
    placeholder: str = ...
    def apply(self, messages: list[AnyMessage], *, count_tokens: TokenCounter) -> None: ...

class ContextEditingMiddleware(AgentMiddleware[AgentState[ResponseT], ContextT, ResponseT]):
    edits: list[ContextEdit]
    token_count_method: Literal['approximate', 'model']
    def __init__(self, *, edits: Iterable[ContextEdit] | None = None, token_count_method: Literal['approximate', 'model'] = 'approximate') -> None: ...
    def wrap_model_call(self, request: ModelRequest[ContextT], handler: Callable[[ModelRequest[ContextT]], ModelResponse[ResponseT]]) -> ModelResponse[ResponseT] | AIMessage: ...
    async def awrap_model_call(self, request: ModelRequest[ContextT], handler: Callable[[ModelRequest[ContextT]], Awaitable[ModelResponse[ResponseT]]]) -> ModelResponse[ResponseT] | AIMessage: ...
