"""
Pydantic data models for structured type-checking and system schema validation.
"""

import uuid

from pydantic import BaseModel, Field
from typing import List, Sequence


class MinimalSource(BaseModel):
    """Represents a minimal spatial fingerprint of a source document.

    Attributes:
        file_path (str): The file path of the indexed document.
        first_character_index (int): The starting index of the chunk.
        last_character_index (int): The ending index of the chunk.
    """
    file_path: str
    first_character_index: int
    last_character_index: int

    def __hash__(self) -> int:
        """Hash a minimal source for easy sets and comparisons."""
        return hash((self.file_path,
                     self.first_character_index,
                     self.last_character_index))


class UnansweredQuestion(BaseModel):
    """Represents a question that has not yet been answered by the system.

    Attributes:
        question_id (str): A unique UUID string identifying the question.
        question (str): The text content of the query.
    """
    question_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    question: str


class AnsweredQuestion(UnansweredQuestion):
    """Represents a question alongside its retrieved sources and LLM answer.

    Attributes:
        sources (List[MinimalSource]): The ground truth or retrieved reference
            chunks.
        answer (str): The expected or generated text answer.
    """
    sources: List[MinimalSource]
    answer: str


class RagDataset(BaseModel):
    """Encapsulates a full dataset containing multiple questions.

    Attributes:
        rag_questions (List[AnsweredQuestion | UnansweredQuestion]): A dataset
            payload.
    """
    rag_questions: List[AnsweredQuestion | UnansweredQuestion]


class MinimalSearchResults(BaseModel):
    """Groups a question with its explicitly retrieved search snippets.

    Attributes:
        question_id (str): The unique identifier from the original query.
        question (str): The text of the query.
        retrieved_sources (List[MinimalSource]): Chunks retrieved by the RAG
            search.
    """
    question_id: str
    question: str
    retrieved_sources: List[MinimalSource]


class MinimalAnswer(MinimalSearchResults):
    """Augments search results with the final LLM-generated answer text.

    Attributes:
        answer (str): The string output generated by the LLM.
    """
    answer: str


class StudentSearchResults(BaseModel):
    """Aggregates all minimal search queries and constraints for evaluation.

    Attributes:
        search_results (Sequence[MinimalSearchResults]): The compiled batch
            results.
        k (int): The number of sources configured per retrieval event.
    """
    search_results: Sequence[MinimalSearchResults]
    k: int


class StudentSearchResultsAndAnswer(StudentSearchResults):
    """Aggregates all answered queries and constraints for the dataset output.

    Attributes:
        search_results (Sequence[MinimalAnswer]): The full final output array.
    """
    search_results: Sequence[MinimalAnswer]


class CodeChunk(BaseModel):
    """
    Combines a segment of text with its corresponding MinimalSource metadata.

    Attributes:
        text (str): The raw text segment extracted from the document.
        source (MinimalSource): Coordinates locating the text segment.
    """
    text: str
    source: MinimalSource
